server:
  http_listen_port: 9080
  grpc_listen_port: 0
  http_listen_address: "0.0.0.0"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets: [ localhost ]
        labels:
          job: varlogs
          __path__: /var/log/**/*.log

  # read docker logs via docker socket. this config can be removed if container logs aren't needed (eg, using otel-native logs)
  # removing this config allows removing the docker.sock bind-mount from docker-compose
  - job_name: docker_containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: { }
    relabel_configs:
      - target_label: job
        replacement: docker_sock
      - source_labels: [ __meta_docker_container_name ]
        target_label: container_name
